import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import { StompClientProvider } from '@/ws/StompClientContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link href="https://api.fontshare.com/v2/css?f[]=supreme@800,400,100,500,1,700&display=swap" rel="stylesheet"></link>
      <body className={inter.className}>
          <div className="">
            <StompClientProvider>

              {children}
              <Toaster></Toaster>
            </StompClientProvider>
          </div>
        </body>
    </html>
  )
}
