import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import { StompClientProvider } from '@/ws/StompClientContext'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className + " h-screen")}>
            <StompClientProvider>

              {children}
              <Toaster></Toaster>
            </StompClientProvider>
        </body>
    </html>
  )
}
